### PR TITLE
Update D08P1_LeetCode_268.py

### PR DESCRIPTION
**Pull request by Pranavbh1**

### CODE REVIEW

**Comment by bansalkanav** [comment]
Kindly find the feedback below:

**Python Solutions/D08P1_LeetCode_268.py** - Compared to the previous submission, your code looks complex and variable names can be improved.

**Python Solutions/D03P2_LeetCode_1281.py** - Variable names can be improved.

**Comment by Pranavbh1** [comment]
D08P1_LeetCode_268.py :- My commit Maybe be complex but it is more robust as in : for sum of n number  we are not iterating for n numbers of time we are just using the mathematical formula for sum of n numbers is : n*(n+1)//2 .
This is simply do arithmetic operation rather than iterating over n times .

**Comment by Pranavbh1** [comment]
D03P2_LeetCode_1281.py : For this i had changed variable names .

**Comment by bansalkanav** [comment]
Yes. I agree the mathematical formula part. 

Your code could be boiled down to:
```python
def fun(nums):
  n = len(nums)
  return ((n*(n+1)//2)-sum(nums))
```

**Comment by Pranavbh1** [comment]
okay will positively do this changes . 
Thanks.

**Pull request closed without merging**
